# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Igor Romanovsky
author: Systems Architect – Azure Cloud
#email: 15823576+iromanovsky@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  I help customers by designing and implementing solutions for Core Infrastructure on Azure Cloud

#https://jekyllrb.com/docs/configuration/options/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://irom.info" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: iromanovsky
github_username:  iromanovsky
linkedin_username: iromanovsky
#rss: Subscribe

# Build settings
theme: minima
#remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-remote-theme

markdown: GFM

# Minima settings
#https://github.com/jekyll/minima
#https://github.com/jekyll/minima/blob/v2.5.1/README.md
show_excerpts: true
google_analytics: G-T6WJFJSCF5
#from v3 only
#author:
#  name: "Igor Romanovsky | Systems Architect – Azure Cloud"
#  email: 15823576+iromanovsky@users.noreply.github.com

#disqus:
#  shortname: my_disqus_shortname

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  #date_format: "%d %b %Y" #"%Y-%m-%d %H:%M" #http://shopify.github.io/liquid/filters/date/ date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/iromanovsky" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/iromanovsky/" }

#https://jekyllrb.com/docs/permalinks/
#permalink: pretty
# :title :name :slug
permalink: /blog/:year/:month/:day/:slug

#https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#https://jekyllrb.com/docs/collections/
collections:
  authors:
    output: true
  reviews:
    output: true
    sort_by: item_order

#https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  # - scope:
  #     path: ""
  #   values:
  #     layout: "default"

