# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Igor Romanovsky
author: Systems Architect ☁️ Azure Cloud
#email: 15823576+iromanovsky@users.noreply.github.com
description: >- # this means to ignore newlines until "baseurl:"
  I help customers by designing and implementing solutions for Core Infrastructure on Azure Cloud

#https://jekyllrb.com/docs/configuration/options/
#https://mademistakes.com/mastering-jekyll/site-url-baseurl/
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://irom.info" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: iromanovsky
#github_username:  iromanovsky #commented to not mix with linkedin
linkedin_username: iromanovsky
#rss: Subscribe

# Build settings
theme: minima
#remote_theme: jekyll/minima
plugins: #https://jekyllrb.com/docs/github-pages/
  - jekyll-feed
  - jekyll-sitemap #https://github.com/jekyll/jekyll-sitemap #https://www.sitemaps.org/protocol.html https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-remote-theme

#https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll
# GitHub Flavored Markdown Spec https://github.github.com/gfm/
#https://github.com/github/jekyll-commonmark-ghpages 
#https://jekyllrb.com/docs/configuration/markdown/
#markdown: GFM #CommonMarkGhPages 

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

# Minima settings
#https://github.com/jekyll/minima
#https://github.com/jekyll/minima/blob/v2.5.1/README.md
show_excerpts: true
google_analytics: G-T6WJFJSCF5
#from v3 only
#author:
#  name: "Igor Romanovsky | Systems Architect – Azure Cloud"
#  email: 15823576+iromanovsky@users.noreply.github.com

#disqus:
#  shortname: my_disqus_shortname

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  #date_format: "%d %b %Y" #"%Y-%m-%d %H:%M" #http://shopify.github.io/liquid/filters/date/ date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/iromanovsky" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/iromanovsky/" }

#https://jekyllrb.com/docs/permalinks/
#permalink: pretty
# :title :name :slug
permalink: /blog/:year/:month/:day/:slug

#https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true

# jekyll-seo-tag specific
#https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
tagline: "Systems Architect – Azure Cloud" #would be used when page.title is not defined
twitter:
  username: iromanovsky #the site's Twitter handle
  #card: summary #the site's default card type
social: #for specifying social profiles -- used on home and about pages 
  name: Igor Romanovsky | Systems Architect – Azure Cloud #https://developers.google.com/search/docs/appearance/site-names
  links: #https://schema.org/sameAs #https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/jekyll-seo-tag/drop.rb
    - https://www.linkedin.com/in/iromanovsky
    - https://github.com/iromanovsky
    - https://twitter.com/iromanovsky

#author: #https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information
#  twitter: iromanovsky # commented to not svrew up jekyll v2 formatting

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#   - README.md #https://jekyllrb.com/docs/configuration/options/#global-configuration
#   - CNAME

collections: #https://jekyllrb.com/docs/collections/
  authors:
    output: true
  msg:
    output: true
    sort_by: item_order
  redir: #https://github.com/jekyll/jekyll-redirect-from
    output: true
    permalink: /go/:name #https://jekyllrb.com/docs/permalinks/#collections

defaults: #https://jekyllrb.com/docs/configuration/front-matter-defaults/
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope: # setting same author on all pages
      path: ""
      type: "pages"
    values:
      author: Igor #https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
  # - scope:
  #     path: ""
  #   values:
  #     layout: "default"

